name: publish formula

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
      formula:
        required: true
      version:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.inputs.branch }}
      FORMULA: ${{ github.event.inputs.formula }}
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Fetch release branch
        run: git fetch origin ${BRANCH}:release --depth 1

      - name: Pin the current version
        run: |
          CURR_URL=$(git show main:Formula/${FORMULA}.rb | gawk '/^ *url/ {print $2}')
          CURR_VER=$(echo $CURR_URL | gawk 'match($0, /v([0-9]+\.[0-9]+\.[0-9]+)/, m) { print m[1] }')
          cp --f ./Formula/${FORMULA}.rb ./Formula/${FORMULA}@${CURR_VER}.rb

      - name: Set the new version
        run: git restore --source release Formula/${FORMULA}.rb

      - name: Set up git user config
        uses: Homebrew/actions/git-user-config@master

      - name: Commit changes
        run: git commit -am "${FORMULA} ${VERSION}"

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        run: git push --delete origin $BRANCH
