name: publish formula

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      BRANCH: ${{ github.event.inputs.branch }}
      FORMULA: ${{ github.event.inputs.formula }}
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up git
        uses: Homebrew/actions/git-user-config@master

      # - run: ls -la
      - run: git branch --show

      - run: |
        CURR_URL=$(git show main:Formula/groot.rb | gawk '/^ *url/ {print $2}')
        CURR_VERSION=$(gawk 'match($0, /v([0-9]+\.[0-9]+\.[0-9]+)/, m) { print m[1] }')
        echo "${CURR_URL}"
        echo "${CURR_VERSION}"

      - run: git checkout ${BRANCH}

      - run: echo "${{ github.event.inputs.branch }}"

      - run: |
          FORMULA=$(echo 'release: groot 0.0.29' | gawk -F ' ' '{print $2}')
          VERSION=$(echo 'release: groot 0.0.29' | gawk -F ' ' '{print $3}')
          echo "${FORMULA}"
          echo "${VERSION}"

      # - name: Update
      #   run:


      # - name: Push commits
      #   uses: Homebrew/actions/git-try-push@master
      #   with:
      #     token: ${{ github.token }}
      #     branch: main
      #
      # - name: Delete branch
      #   if: github.event.pull_request.head.repo.fork == false
      #   run: git push --delete origin $BRANCH

# name: brew pr-pull
#
# on:
#   pull_request_target:
#     types:
#       - labeled
#
# jobs:
#   pr-pull:
#     if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Set up Homebrew
#         uses: Homebrew/actions/setup-homebrew@master
#
#       - name: Set up git
#         uses: Homebrew/actions/git-user-config@master
#
#       - name: Pull bottles
#         env:
#           HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
#           HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
#           HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
#           PULL_REQUEST: ${{ github.event.pull_request.number }}
#         run: brew pr-pull --debug --tap=$GITHUB_REPOSITORY $PULL_REQUEST
#
#       - name: Push commits
#         uses: Homebrew/actions/git-try-push@master
#         with:
#           token: ${{ github.token }}
#           branch: main
#
#       - name: Delete branch
#         if: github.event.pull_request.head.repo.fork == false
#         env:
#           BRANCH: ${{ github.event.pull_request.head.ref }}
#         run: git push --delete origin $BRANCH
